from __future__ import annotations


def emit_runtime() -> list[str]:
    """Return assembly lines for the Vela runtime library."""
    lines: list[str] = []
    lines.extend(_emit_syscall())
    lines.append("")
    lines.extend(_emit_vdispatch())
    lines.append("")
    lines.extend(_emit_malloc())
    lines.append("")
    lines.extend(_emit_free())
    return lines


def _emit_syscall() -> list[str]:
    return [
        "__syscall:",
        "    SAVEM R0, [__syscall_param]",
        "    SAVEM R1, [__syscall_id]",
        "    MOV PC, R14",
    ]


def _emit_vdispatch() -> list[str]:
    return [
        "__vdispatch:",
        "    MOV PC, R12",
    ]


def _emit_malloc() -> list[str]:
    """Free-list allocator with splitting and stack-heap collision check.

    Input:  R0 = requested size in bytes
    Output: R0 = pointer to usable memory (past 4-byte header), or 0 on failure

    Block header layout (4 bytes):
      [0-1] block_size  (U16, total including header)
      [2-3] next_free   (U16, 0 = in-use or end of list)
    """
    return [
        "__malloc:",
        "    # Prologue",
        "    SUB SP, SP, V2",
        "    SAVEM R14, [SP]",
        "    SUB SP, SP, V2",
        "    SAVEM R11, [SP]",
        "    MOV R11, SP",
        "    SUB SP, SP, V2",
        "    SAVEM R4, [SP]",
        "    SUB SP, SP, V2",
        "    SAVEM R5, [SP]",
        "    SUB SP, SP, V2",
        "    SAVEM R6, [SP]",
        "    SUB SP, SP, V2",
        "    SAVEM R7, [SP]",
        "",
        "    # R0 = requested size, add 4 for header",
        "    ADD R4, R0, V4",
        "    # R5 = pointer to current free block header",
        "    MOVM R5, [__free_list_head]",
        "    # R6 = previous block pointer (0 = head)",
        "    MOV R6, V0",
        "",
        "    # If free list is empty, try to extend heap",
        "    CMP R5, V0",
        "    BEQ __malloc_extend",
        "",
        "__malloc_walk:",
        "    # Read block_size at [R5]",
        "    MOVM R7, [R5]",
        "    # Check if block is big enough",
        "    CMP R7, R4",
        "    BGE __malloc_found",
        "    # Move to next: R6 = R5, R5 = next_free",
        "    MOV R6, R5",
        "    ADD R5, R5, V2",
        "    MOVM R5, [R5]",
        "    CMP R5, V0",
        "    BNE __malloc_walk",
        "",
        "__malloc_extend:",
        "    # Extend heap: allocate at __heap_start",
        "    MOVM R5, [__heap_start]",
        "    CMP R5, V0",
        "    BNE __malloc_ext_check",
        "    # Initialize heap start (after data section)",
        "    MOV R5, V512",
        "",
        "__malloc_ext_check:",
        "    # Stack-heap collision: R5 + R4 must be < SP",
        "    ADD R7, R5, R4",
        "    CMP R7, SP",
        "    BCS __malloc_fail",
        "    # Write block header",
        "    SAVEM R4, [R5]",
        "    # Mark as in-use (next_free = 0)",
        "    ADD R7, R5, V2",
        "    MOV R3, V0",
        "    SAVEM R3, [R7]",
        "    # Update heap_start",
        "    ADD R7, R5, R4",
        "    SAVEM R7, [__heap_start]",
        "    # Return pointer past header",
        "    ADD R0, R5, V4",
        "    B __malloc_done",
        "",
        "__malloc_found:",
        "    # Block at R5 is big enough.",
        "    # Check if we should split (remaining >= 8 bytes)",
        "    SUB R7, R7, R4",
        "    CMP R7, V8",
        "    BLT __malloc_use_whole",
        "    # Split: shrink current block, create new free block after",
        "    SAVEM R4, [R5]",
        "    ADD R3, R5, R4",
        "    SAVEM R7, [R3]",
        "    # New block's next_free = old next_free",
        "    ADD R7, R5, V2",
        "    MOVM R7, [R7]",
        "    ADD R3, R3, V2",
        "    SAVEM R7, [R3]",
        "    # Patch previous to point to new free block",
        "    SUB R3, R3, V2",
        "    CMP R6, V0",
        "    BEQ __malloc_split_head",
        "    ADD R6, R6, V2",
        "    SAVEM R3, [R6]",
        "    B __malloc_use_block",
        "__malloc_split_head:",
        "    SAVEM R3, [__free_list_head]",
        "    B __malloc_use_block",
        "",
        "__malloc_use_whole:",
        "    # Use the whole block — unlink from free list",
        "    ADD R7, R5, V2",
        "    MOVM R7, [R7]",
        "    CMP R6, V0",
        "    BEQ __malloc_unlink_head",
        "    ADD R6, R6, V2",
        "    SAVEM R7, [R6]",
        "    B __malloc_use_block",
        "__malloc_unlink_head:",
        "    SAVEM R7, [__free_list_head]",
        "",
        "__malloc_use_block:",
        "    # Mark block as in-use",
        "    ADD R7, R5, V2",
        "    MOV R3, V0",
        "    SAVEM R3, [R7]",
        "    # Return usable pointer",
        "    ADD R0, R5, V4",
        "    B __malloc_done",
        "",
        "__malloc_fail:",
        "    MOV R0, V0",
        "",
        "__malloc_done:",
        "    # Epilogue",
        "    MOV SP, R11",
        "    SUB SP, SP, V8",
        "    MOVM R7, [SP]",
        "    ADD SP, SP, V2",
        "    MOVM R6, [SP]",
        "    ADD SP, SP, V2",
        "    MOVM R5, [SP]",
        "    ADD SP, SP, V2",
        "    MOVM R4, [SP]",
        "    ADD SP, SP, V2",
        "    MOVM R11, [SP]",
        "    ADD SP, SP, V2",
        "    MOVM R14, [SP]",
        "    ADD SP, SP, V2",
        "    MOV PC, R14",
    ]


def _emit_free() -> list[str]:
    """Free-list deallocator with address-sorted insertion and coalescing.

    Input: R0 = pointer to usable memory (as returned by __malloc)
    """
    return [
        "__free:",
        "    # Prologue",
        "    SUB SP, SP, V2",
        "    SAVEM R14, [SP]",
        "    SUB SP, SP, V2",
        "    SAVEM R11, [SP]",
        "    MOV R11, SP",
        "    SUB SP, SP, V2",
        "    SAVEM R4, [SP]",
        "    SUB SP, SP, V2",
        "    SAVEM R5, [SP]",
        "    SUB SP, SP, V2",
        "    SAVEM R6, [SP]",
        "",
        "    # R0 points to usable area, subtract 4 to get header",
        "    SUB R4, R0, V4",
        "    # R5 = current free list pointer",
        "    MOVM R5, [__free_list_head]",
        "    # R6 = previous pointer",
        "    MOV R6, V0",
        "",
        "    # Find insertion point (sorted by address)",
        "    CMP R5, V0",
        "    BEQ __free_insert_head",
        "",
        "__free_find:",
        "    CMP R4, R5",
        "    BLT __free_insert",
        "    MOV R6, R5",
        "    ADD R5, R5, V2",
        "    MOVM R5, [R5]",
        "    CMP R5, V0",
        "    BNE __free_find",
        "",
        "__free_insert:",
        "    # Insert R4 between R6 and R5",
        "    ADD R3, R4, V2",
        "    SAVEM R5, [R3]",
        "    CMP R6, V0",
        "    BEQ __free_set_head",
        "    ADD R6, R6, V2",
        "    SAVEM R4, [R6]",
        "    B __free_coalesce",
        "",
        "__free_insert_head:",
        "    # Free list was empty — set R4->next = 0 then fall through",
        "    ADD R3, R4, V2",
        "    SAVEM R5, [R3]",
        "",
        "__free_set_head:",
        "    # Set R4 as the new free list head",
        "    SAVEM R4, [__free_list_head]",
        "",
        "__free_coalesce:",
        "    # Try to coalesce with next block",
        "    MOVM R3, [R4]",
        "    ADD R3, R4, R3",
        "    CMP R3, R5",
        "    BNE __free_done",
        "    CMP R5, V0",
        "    BEQ __free_done",
        "    # Merge: add next block's size to current",
        "    MOVM R3, [R4]",
        "    MOVM R6, [R5]",
        "    ADD R3, R3, R6",
        "    SAVEM R3, [R4]",
        "    # Skip next block in free list",
        "    ADD R5, R5, V2",
        "    MOVM R5, [R5]",
        "    ADD R3, R4, V2",
        "    SAVEM R5, [R3]",
        "",
        "__free_done:",
        "    # Epilogue",
        "    MOV SP, R11",
        "    SUB SP, SP, V6",
        "    MOVM R6, [SP]",
        "    ADD SP, SP, V2",
        "    MOVM R5, [SP]",
        "    ADD SP, SP, V2",
        "    MOVM R4, [SP]",
        "    ADD SP, SP, V2",
        "    MOVM R11, [SP]",
        "    ADD SP, SP, V2",
        "    MOVM R14, [SP]",
        "    ADD SP, SP, V2",
        "    MOV PC, R14",
    ]
